### ISSUE TITLE
Several nutrients missing

### ISSUE THREAD

**Issue by christianfl** [openfoodfacts/openfoodfacts-dart#166]
Hey guys! Thanks for this dart package, it's really helpful. Currently I am developing a food tracking app (with micronutrients) and noticed that several nutrients fields and their units / serving sizes are missing which are there in the API (https://static.openfoodfacts.org/data/data-fields.txt). 

- pantothenic-acid_100g
- biotin_100g
- chloride_100g
- chromium_100g
- fluoride_100g
- iodine_100g
- manganese_100g
- molybdenum_100g
- omega-3-fat_100g
- omega-6-fat_100g
- trans-fat_100g

**Comment by monsieurtanuki** [comment]
Hello @christianfl!
Working on it.
Could you please give me some barcodes that are expected to have relevant values for those nutrients? For testing purposes.

**Comment by christianfl** [comment]
Hey @monsieurtanuki 

Thank you really much! Of course, I will provide you with that. But I'm just mildly irritated, could you tell me wether I understand this API fields correctly before?

1. E.g. "vitamin-b12_100g" = how many **g** of Vitamin B12 are there in **100g** of product
2. E.g. "vitamin-b12_unit" and "vitamin-b12_value" are just another representation of 1. Could be e.g. "µg" and "12"
3. What API field corresponds to e.g. "vitaminB12Serving" in this dart plugin then, is this the value from 2?

**Comment by monsieurtanuki** [comment]
@christianfl Honestly I'm not 100% sure, it's the first time I code in that class.

From what I knew before and what I've just tested on https://fr.openfoodfacts.org/produit/5411188115496/soja-milch-alpro and https://fr.openfoodfacts.org/produit/0038900009472/vicks-pure-zzzs-melatonin-gummies-dole, for a product whose serving is 250g:
* `Unit? vitaminB12Unit` (`'vitamin-b12_unit'`) is the typical unit for vitamin B12 (e.g. `'µg'`) (I don't know if it changes according to products, probably not often)
* `double? vitaminB12` (`'vitamin-b12_100g'`) is the value _in grams_ of vitamin B12 _for the standard 100g_ of this product (e.g. `0.000001`) (that means `0.000001g`, or `1µg`)
* `double? vitaminB12Serving` (`'vitamin-b12_serving'`) is the value _in grams_ of vitamin B12 _for the typical serving_ (here, 250g) of this product (e.g. `0.0000025`) (that means `0.0000025g`, or `2.5µg`) (looks like `product.vitaminB12 / 100 * product.servingQuantity`)

"Serving" data is very interesting if you want to compare products that you actually eat. For instance if cinnamon has a lot of vitamin B12 for 100g (which I've just invented), that's not interesting because you don't eat 100g of cinnamon, but rather 5g.

**Comment by christianfl** [comment]
Thanks, that clarified much for me. See the table below for the nutrients I found:

| Nutrient         | nutrient_100g_name    | EAN example   | nutrient_100g (value) | nutrient_unit (value) | nutrient_serving (value) |
|------------------|-----------------------|---------------|---------------------|---------------------|------------------------|
| pantothenic-acid | pantothenic-acid_100g | 5060517883638 | 0.0042              | "mg"                |                        |
| biotin           | biotin_100g           | 7612100018477 | 0.0000165           | "&#181;g"           |                        |
| chloride         | chloride_100g         | 3057640257773 | 0.015               | "mg"                | 0.15                   |
| chromium         | chromium_100g         | 4260556630007 | 0.000002            | "µg"                | 0.00001                |
| iodine           | iodine_100g           | 4260556630007 | 0.0000075           | "µg"                | 0.0000375              |
| manganese        | manganese_100g        | 4260556630007 | 0.0001              | "mg"                | 0.0005                 |
| molybdenum       | molybdenum_100g       | 4260556630007 | 0.000004            | "µg"                | 0.00002                |
| omega-3-fat      | omega-3-fat_100g      | 336632105236  | 3.2                 | "g"                 | 0.32                   |
| omega-6-fat      | omega-6-fat_100g      | 3155251205319 | 9.1                 | "g"                 | 9.1                    |
| trans-fat        | trans-fat_100g        | 5000159461122 | 0.1                 | "g"                 | 0.05                   |

**Comment by monsieurtanuki** [comment]
Thank you @christianfl for the examples from which I populated the tests. Still missing: a product with fluoride data. We'll survive, though.
Done in #186.
