### ISSUE TITLE
Invalid barcodes blocklist

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#188]
Implement the invalid barcodes blocklist

The barcode scanners will return invalid barcodes due to bright reflections, poor lighting, etc…

While those barcodes are theoretically valid EAN-8 barcodes, they are not attributed. We are thus putting in place a server side blacklist of common invalid barcodes, so that the app doesn't return a prompt to add a blacklisted product, or return a result for an invalid product once someone has created it.

https://world.openfoodfacts.org/data/invalid-barcodes.json
The desired behaviour is to do as if nothing had been scanned (and also probably to not send the query.)

**Comment by monsieurtanuki** [comment]
@teolemon Is it always going to be a small list like the current one (11 items), or maybe some day blacklisted items could also be determined with regexp? Instead of a veryyyyyy long list.

**Comment by teolemon** [comment]
@monsieurtanuki we haven't expanded the list in ages. The idea was to attack the top 50 of invalid barcodes. 
The issue with a regex approach is that those barcodes are theoretically valid EAN-8 barcodes. So there's no way to tell them apart.

**Comment by monsieurtanuki** [comment]
I guess we can handle this like the other json referentials like https://world.openfoodfacts.org/api/v2/preferences?lc=$language and https://world.openfoodfacts.org/api/v2/attribute_groups?lc=$language.

Or if the list doesn't expand that often and stays small, that would make sense to include it as is in OFF-dart, like a simple `static const List<String>`. Instead of a painful and useless server lookup.

**Comment by monsieurtanuki** [comment]
I've just implemented the invalid barcode list in #195.
What can be done next? We have no control of how the developer scans and deals with the scanned barcodes, have we?

**Comment by stephanegigandet** [comment]
> What can be done next? We have no control of how the developer scans and deals with the scanned barcodes, have we?

We could send back a special error message for product queries for one of those barcodes I guess. But ideally the best behaviour is for developers to deal with it in their app (essentially discarding scan results that match one of the barcodes).

**Comment by monsieurtanuki** [comment]
@stephanegigandet Then now it's more about docs and examples than actual code, right?

And I cannot see how to prevent them from accessing those barcodes within OFF-dart: that would mean an extra `InvalidBarcodes` parameter for each method...

Or we stick to my favorite "good enough is good enough" saying, and we do check that inside OFF-dart, with the [`base` version of `InvalidBarcodes`](https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/lib/utils/InvalidBarcodes.dart#L25-L52) (just 11 barcodes, that can be accessed like a `static const` instead of a http json).

**Comment by teolemon** [comment]
I consider this one fixed. Thanks @monsieurtanuki
