### ISSUE TITLE
kcal / kj

### ISSUE THREAD

**Issue by adfaure** [openfoodfacts/openfoodfacts-dart#44]
Hello,
is there a reason why the kcal value is not present in the nutriments class?

I saw that one can convert from KJ to kcal.
Is it a better option do to the conversion, or to add this value into the nutriment class to access the value returned by OFF API?

Thank you,
Adrien

**Comment by PrimaelQuemerais** [comment]
Hi Adrien,
I think the reason why the field is not present in the nutrition class is sometimes the API doesn't return the value in kcal, in the use-case I was working on at the time it made sens to only use the kj field.

Of course we can add the kcal field as it might be usefull for others. Do you want to make a PR ? Otherwise I'll add the field in the next version of the plugin

**Comment by adfaure** [comment]
Hello, thank you for your reply.
Indeed, it makes sense.

I already did it on a clone, 
I'll do a merge request within the day.

**Comment by PrimaelQuemerais** [comment]
Great! Thank you for helping, I'll merge you'r PR and update the plugin as soon as I can.

**Comment by PrimaelQuemerais** [comment]
Merged
