### ISSUE TITLE
❌ test/api_saveProduct_test.dart: OpenFoodAPIClient add new products add new product test 5 (failed)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#500]
### What
❌ test/api_saveProduct_test.dart: OpenFoodAPIClient add new products add new product test 5 (failed)
  Expected: <1>
    Actual: <400>
  
  package:test_api                      expect
  test/api_saveProduct_test.dart 264:7  main.<fn>.<fn>

**Comment by monsieurtanuki** [comment]
@teolemon The problem is probably on the server side.
Like "it's such a lousy product (very few data) that when we try to compute the scores, we fail (with a time-out)".

Even the website itself crashes when we just add a nutrient value: https://world.openfoodfacts.net/product/7340011364184/chili-beans-null (off/off)

When I try, I get a time-out:
```
504 Gateway Time-out
nginx/1.21.6
```

And if I go back to the product page, I see that my change has been made.

For the record, those were the nutrients currently with data:
* Energy (kJ)
* Fat
* Saturated fat
* Carbohydrates
* Sugars
* Proteins
* Alcohol
* Vitamin B12 (cobalamin)

And the completion states are:
* Done
  * Nutrition facts completed
  * Categories completed
  * Brands completed
  * Packaging completed
  * Product name completed
* To do
  * To be completed
  * Ingredients to be completed
  * Expiration date to be completed
  * Packaging code to be completed
  * Characteristics to be completed
  * Origins to be completed
  * Quantity to be completed
  * Photos to be uploaded

**Comment by teolemon** [comment]
ok, closing

**Comment by monsieurtanuki** [comment]
Now it's skipped.
