### ISSUE TITLE
Check we are not sending credentials in the wrong conditions

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#553]
### What

- [ ] Check we are not sending credentials in the wrong conditions
  - [ ] is provoking https://github.com/openfoodfacts/smooth-app/issues/2793
  - [ ] is a privacy issue
- [ ] Check we're sending the right kind of authentication (eg Robotoff does not need the regular auth)
  - [ ] Probably provoking openfoodfacts/smooth-app#2954 where Robotoff considers the query a vote, meaning it did not recognize the user

**Comment by teolemon** [comment]
anything that's READ should not have any auth
anything WRITE: user_id + password
Robotoff: 

  static Future<Status> postInsightAnnotation(
    String? insightId,
    InsightAnnotation annotation, {
    User? user,
    String? deviceId,
    bool update = true,
    final QueryType? queryType,
  }) async {
    var insightUri = UriHelper.getRobotoffUri(
      path: 'api/v1/insights/annotate',
      queryType: queryType,
    );

  static Future<SpellingCorrection?> getIngredientSpellingCorrection({
    String? ingredientName,
    Product? product,
    User? user,
    QueryType? queryType,
  }) async {
    Map<String, String> spellingCorrectionParam;

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/robotoff/blob/master/robotoff/app/api.py#L209

**Comment by raphael0202** [comment]
Linked to https://github.com/openfoodfacts/openfoodfacts-dart/issues/560
Robotoff question answers are still sent as vote. It's because we don't seem to send any authentication (https://github.com/openfoodfacts/openfoodfacts-dart/blob/a826add65c6b993f748b2874ef501a5efc900497/lib/openfoodfacts.dart#L618).

Robotoff supports HTTP Basic authentication, so we can authenticate the user this way:
send a `Authorization:'basic {ENCODEDBASE64}' `header where `{ENCODEDBASE64}` is an base64-encoded string of `user:password`. The answer from the server should be (in case of a positive annotation):

```json
{
    "description": "the annotation was saved and sent to OFF",
    "status": "updated",
    "status_code": 2
}
```

**Comment by monsieurtanuki** [comment]
@M123-dev I don't know how exactly they are related but since #590 is merged what is the next step here?

**Comment by M123-dev** [comment]
This should be mostly done, the only open question from #590 was if we should also send credentials to read queries

**Comment by raphael0202** [comment]
No, credentials shouldn't be sent to read queries

**Comment by M123-dev** [comment]
Perfect, then we are done here and after https://github.com/openfoodfacts/smooth-app/pull/3211 also with https://github.com/openfoodfacts/smooth-app/issues/2954
