### ISSUE TITLE
Find a better way to handle language specific fields (e.g. product_name, ingredients_text)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-dart#62]
The Product class has fields like:

      this.productName,
      this.productNameDE,
      this.productNameEN,
      this.productNameFR,
      this.brands,
      this.lang,
      this.quantity,
      this.imgSmallUrl,
      this.ingredientsText,
      this.ingredientsTextDE,
      this.ingredientsTextEN,

productNameDE is mapped to the product_name_de field we retrieve from the API.

But in practice, OFF contains product data in 200 languages, it doesn't make sense to have 200 fields for product name, for ingredients, for packagings, for generic name etc.

We could change the Product class so that all language specific fields are a map, with language code as keys. But that would mean we would need to check if "product_name_[language code]" exists in the JSON to populate the map, and most of them won't exist.

Instead, I think we could just remove the productNameDE etc. fields and just provide getter functions that will check in the json object whenever they get called. Something like getFieldInLanguage(PRODUCT_NAME, "de") that we could call on all language specific fields, (with PRODUCT_NAME a constant for "product_name", that we can concatenate with the language to access the right field in the JSON)

There is a similar issue for images.

**Comment by PrimaelQuemerais** [comment]
The fields productNameDE, productNameEN, ... are somehow deprecated since we introduced the OpenFoodFactsLanguage parameter to the queries. The productName field will contain the product name in the specified OpenFoodFactsLanguage.

Do we need to provide a way to retrieve the product name in multiple languages in one query?

**Comment by stephanegigandet** [comment]
I wasn't aware of that, maybe we should explicitly mention that they are deprecated and should not be used in new apps.

I will have to look at how the OpenFoodFactsLanguage parameter works.

> Do we need to provide a way to retrieve the product name in multiple languages in one query?

I don't think so.

**Comment by PrimaelQuemerais** [comment]
I think I can simply remove them in the next version, the dart dependencies manager will take care of showing the deprecated fields. Also knowing how the `OpenFoodFactsLanguage` is used in the query system I'm pretty sure most developers already use it.

`OpenFoodFactsLanguage` is basically an object version of the languages taxonomy so that developers can access every languages without having to know the country code.

Closing this issue for now we can reopen it if necessary
