### ISSUE TITLE
Use fixed data for the tests

### ISSUE THREAD

**Issue by MohamedFBoussaid** [openfoodfacts/openfoodfacts-dart#78]
Today the tests are using products from the OFF DB. And with time those products are getting updated by the community, which lead to instable tests. 
Maybe using mock data, a test DB if it existe or a Read-Only products to make the tests stable.

**Comment by peterwvj** [comment]
I completely agree. I think issue should be fixed before anything else.

**Comment by stephanegigandet** [comment]
We do have a test database on world.openfoodfacts.net (it needs an extra layer of HTTP authorization with login and password off)

One thing we could do is to require apps to create an instance of OpenFoodApiClient and indicate if they want to use the testing database in the constructor call.

We could then make the static methods normal methods (e.g.   static Future<Status> saveProduct(User user, Product product) etc.), so that we can use the proper host.

That would require a small change from apps though.

Then on that database, the tests could first write the fields, and then read them back, so that test pass even if someone else has changed a product.

**Comment by MohamedFBoussaid** [comment]
@stephanegigandet, I guess your proposal is the best way to approach this. It will improve 2 things in once fix. The test package on the openfoodfact-dart, and apps can use it during the developing stage.

**Comment by MohamedFBoussaid** [comment]
Fixed with the #83. The issue can be closed.
