### ISSUE TITLE
Add support for the upcoming user info API

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#893]
### Description
Add support for the upcoming user info API
https://github.com/openfoodfacts/openfoodfacts-server/pull/9918

**Comment by stephanegigandet** [comment]
Note that we are planning to remove the email from the body. Is it needed for the app? cc @monsieurtanuki @g123k

**Comment by monsieurtanuki** [comment]
> Note that we are planning to remove the email from the body. Is it needed for the app? cc @monsieurtanuki @g123k

@stephanegigandet In Smoothie we don't need the user email field returned by `/cgi/auth.pl`:
* we only use `/cgi/auth.pl` once, in off-dart's method `login2`
* we only use method `login2` once, in Smoothie's method `getLoginResult`
* inside method `getLoginResult`, we only extract the `user_id` field

In Smoothie the user may log in with the user id or the email (same password).

Actually, from https://github.com/openfoodfacts/smooth-app/issues/2464 https://github.com/openfoodfacts/smooth-app/pull/3499 we explicitly use the returned `user_id` field instead of whatever the user typed in (user id or email) because it created side-effects to use user email.

Possible confusion: is the returned `user_id` always a "decent" user id - and never an email?

**Comment by stephanegigandet** [comment]
@monsieurtanuki Perfect, thanks for checking, I will remove the email field.
The returned user_id is always the user id, never an email
